# -*- mode: shell-script[zsh]; -*-
#
# Summary: Initializes and exports all relevant environment variables.

export ZSH_CONFIG_DIR="$HOME/.zsh.d"

APP_DIR="$HOME/Apps"
BIN_DIR="$HOME/bin"

export BROWSER="/usr/bin/firefox"
export EDITOR="/usr/bin/emacs"
export GRADLE_HOME="$APP_DIR/Gradle"
export M2_HOME="$APP_DIR/Maven"
export M2="$M2_HOME/bin"
export LESS="-R -M -# 5"
export PAGER="/usr/bin/less"
export R_LIBS="$HOME/.local/share/R"
export RB_ENV_HOME="$HOME/.rbenv"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export ZSH_CACHE_HOME="$XDG_CACHE_HOME/zsh"

typeset -gxU fpath FPATH
typeset -gxU path PATH

fpath=($ZSH_CONFIG_DIR/functions $fpath)
path=($BIN_DIR $path)
