# -*- mode: shell-script[zsh] -*-
#
# Summary: Initializes all relevant user configuration options in ZSH.

[[ -z "$PS1" ]] && return

source $ZSH_CONFIG_DIR/shell/use-config.zsh

use-config aliases     shell
use-config completion  shell
use-config history     shell
use-config keybindings shell
use-config prompt      shell
