# -*- mode: shell-script[zsh] -*-
#
# Summary: Initializes all relevant user configuration options in ZSH.

[[ -z "$PS1" ]] && return

source $ZSH_CONFIG_DIR/lib/messages.zsh
source $ZSH_CONFIG_DIR/lib/use-config.zsh

use-config aliases     shell
use-config completion  shell
use-config history     shell
use-config keybindings shell
use-config prompt      shell

use-config functions   shell/extra
use-config ruby        shell/extra
